name: heroku

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - run: git config --global user.name "xacti"
      - run: git config --global user.email "xacti@email.com"
      - run: git pull origin master
      - run: git checkout -b heroku
      - run: git push -f origin heroku
        env:
          CI: true